// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC--Uyx6sdUyYhYA3iMVY-46Ps5nIb5600',
    appId: '1:659773925482:web:fa27564b5f3089e689c213',
    messagingSenderId: '659773925482',
    projectId: 'toodle-d2886',
    authDomain: 'toodle-d2886.firebaseapp.com',
    storageBucket: 'toodle-d2886.appspot.com',
    measurementId: 'G-QNZQGHZ9SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG6ykOAlUI0VOZSDvqyA5rC01vuwVAmug',
    appId: '1:659773925482:android:4114d3fa84f81cfa89c213',
    messagingSenderId: '659773925482',
    projectId: 'toodle-d2886',
    storageBucket: 'toodle-d2886.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxyZkeW0UfUNbB7PA2aUVBwbCr827kwPg',
    appId: '1:659773925482:ios:0f72f912c4a327c889c213',
    messagingSenderId: '659773925482',
    projectId: 'toodle-d2886',
    storageBucket: 'toodle-d2886.appspot.com',
    iosClientId: '659773925482-dm2i2kbvd3r74bukcttdjj308kc87f91.apps.googleusercontent.com',
    iosBundleId: 'com.example.toddle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxyZkeW0UfUNbB7PA2aUVBwbCr827kwPg',
    appId: '1:659773925482:ios:0f72f912c4a327c889c213',
    messagingSenderId: '659773925482',
    projectId: 'toodle-d2886',
    storageBucket: 'toodle-d2886.appspot.com',
    iosClientId: '659773925482-dm2i2kbvd3r74bukcttdjj308kc87f91.apps.googleusercontent.com',
    iosBundleId: 'com.example.toddle',
  );
}
